CC=g++
CFLAGS=-c -Wall
LDFLAGS=
SOURCES=arithmetic.h arithmetic.cpp hw1_p2.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=hw1_p2

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

