CC=g++
CFLAGS=-c -Wall
LDFLAGS=
SOURCES=huffman.h huffman.cpp hw1_p1.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=hw1_p1

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@
